site:
  name: Kwan Website

media:
  input: src/assets
  output: /assets

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: '{fields.slug}.md'
    view:
      fields: [ title, slug, source ]
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: source
        label: Source
        type: select
        options: [ cms, google-doc-embed, google-doc-fetch ]
      - name: googleDocId
        label: Google Doc ID
        type: string
      - name: body
        label: Body
        type: markdown

  - name: publications
    label: Publications
    type: collection
    path: src/content/publications
    filename: '{year}-{fields.slug}.md'
    view:
      fields: [ title, year ]
    fields:
      - name: title
        label: Title
        type: string
      - name: slug
        label: Slug
        type: string
      - name: authors
        label: Authors
        type: list
        fields:
          - name: author
            label: Author
            type: string
      - name: venue
        label: Journal/Publisher
        type: string
      - name: year
        label: Year
        type: number
      - name: doi
        label: DOI/Link
        type: string
      - name: abstract
        label: Abstract
        type: text
      - name: cover
        label: Cover Image
        type: image

  - name: site
    label: Site Settings
    type: file
    path: src/config/site.json
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: string
