media:
  input: src/assets/cms
  output: /assets/cms

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: "{fields.slug}.md"
    view:
      fields: [ title, slug, source ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        pattern: ^[a-z0-9-]+$
        required: true
      - name: source
        label: Source
        type: select
        options:
          - label: CMS Markdown
            value: cms
          - label: Google Doc (embed)
            value: google-doc-embed
          - label: Google Doc (fetch text)
            value: google-doc-fetch
        required: false
      - name: googleDocId
        label: Google Doc ID
        type: string
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text

  - name: publications
    label: Publications
    type: collection
    path: src/content/publications
    filename: "{year}-{fields.slug}.md"
    view:
      fields: [ title, year ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        pattern: ^[a-z0-9-]+$
        required: true
      - name: authors
        label: Authors
        type: list
        fields:
          - name: author
            label: Author
            type: string
      - name: venue
        label: Journal/Publisher
        type: string
      - name: year
        label: Year
        type: number
      - name: doi
        label: DOI/Link
        type: string
      - name: abstract
        label: Abstract
        type: text
      - name: cover
        label: Cover Image
        type: image

  - name: site
    label: Site Settings
    type: file
    path: src/config/site.json
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: string
