media:
  input: src/assets/cms
  output: /assets/cms

content:
  - name: pages
    label: Pages
    type: collection
    path: src/content/pages
    filename: "{fields.slug}.md"
    view:
      fields: [ title, slug ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        pattern: ^[a-z0-9-]+$
        required: true
      - name: heroImage
        label: Hero Image
        type: image
      - name: body
        label: Body
        type: rich-text

  - name: publications
    label: Publications
    type: collection
    path: src/content/publications
    filename: "{year}-{fields.slug}.md"
    view:
      fields: [ title, year ]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        pattern: ^[a-z0-9-]+$
        required: true
      - name: authors
        label: Authors
        type: list
        fields:
          - name: author
            label: Author
            type: string
      - name: venue
        label: Journal/Publisher
        type: string
      - name: year
        label: Year
        type: number
      - name: doi
        label: DOI/Link
        type: string
      - name: abstract
        label: Abstract
        type: text
      - name: cover
        label: Cover Image
        type: image

  - name: site
    label: Site Settings
    type: file
    path: src/config/site.json
    fields:
      - name: title
        label: Website Title
        type: string
      - name: description
        label: Website Description
        type: string
